# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - eureka-server-bc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://everisbank.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5c1f675997bf43d9b9e12d0dc1c24584 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1181dd0edc0d4279abe8c474537ba5c0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: everisbank.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5c1f675997bf43d9b9e12d0dc1c24584 }}/bc-eureka-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'eureka-server-bc'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cde83a936a4c40c5968d43827e4b157a }}
        images: 'everisbank.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5c1f675997bf43d9b9e12d0dc1c24584 }}/bc-eureka-server:${{ github.sha }}'