# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - bc-eureka-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
#    permissions:
#      packages: write
#      contents: read

    steps:
#    - uses: actions/checkout@v2
#    - name: Set up JDK 11
#      uses: actions/setup-java@v2
#      with:
#        java-version: '11'
#        distribution: 'adopt'
#    - name: Build with Maven
#      run: mvn package --file pom.xml

#    - name: Build with Maven
#      run: mvn --batch-mode --update-snapshots verify
#
#    - name: Verify file project
#      run: ls -l
#
#    - name: Copy Jar
#      run: cp `ls -d`/target/*.jar app.jar
#
#    - name: Verify file project
#      run: ls -l
#
#    - uses: actions/upload-artifact@v2
#      with:
#        name: Package
#        path: staging

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://everisbank.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_943b5aa688f34806a7f582a71ba2525b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_845a0ac1f036454ba9ea1d7f95296800 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: everisbank.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_943b5aa688f34806a7f582a71ba2525b }}/bc-eureka-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bc-eureka-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_86b4e0a1a80945df964e3a1810ce0bcd }}
        images: 'everisbank.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_943b5aa688f34806a7f582a71ba2525b }}/bc-eureka-server:${{ github.sha }}'