# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

#name: Build and deploy container app to Azure Web App - bc-eureka-server
#
#on:
#  push:
#    branches:
#      - main
#  workflow_dispatch:
#
#jobs:
#  build:
#    runs-on: 'ubuntu-latest'


#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up JDK 11
#      uses: actions/setup-java@v2
#      with:
#        java-version: '11'
#        distribution: 'adopt'
#    - run: mvn --batch-mode --update-snapshots verify
#    - run: mkdir staging && cp target/*.jar staging
#    - uses: actions/upload-artifact@v2
#      with:
#       name: Package
#       path: staging
#
##    - name: Cache Maven packages
##      uses: actions/cache@v2
##      with:
##        path: ~/.m2
##        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
##        restore-keys: ${{ runner.os }}-m2
#
##    - name: Build with Maven
##      run: mvn --batch-mode --update-snapshots verify
#
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v1
#
#    - name: Log in to registry
#      uses: docker/login-action@v1
#      with:
#        registry: https://everisbank.azurecr.io/
#        username: ${{ secrets.AzureAppService_ContainerUsername_943b5aa688f34806a7f582a71ba2525b }}
#        password: ${{ secrets.AzureAppService_ContainerPassword_845a0ac1f036454ba9ea1d7f95296800 }}
#
#    - name: Build and push container image to registry
#      uses: docker/build-push-action@v2
#      with:
#        context: ./
#        push: true
#        tags: everisbank.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_943b5aa688f34806a7f582a71ba2525b }}/bc-eureka-server:${{ github.sha }}
#        file: ./Dockerfile
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    environment:
#      name: 'production'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#
#    steps:
#    - name: Deploy to Azure Web App
#      id: deploy-to-webapp
#      uses: azure/webapps-deploy@v2
#      with:
#        app-name: 'bc-eureka-server'
#        slot-name: 'production'
#        publish-profile: ${{ secrets.AzureAppService_PublishProfile_86b4e0a1a80945df964e3a1810ce0bcd }}
#        images: 'everisbank.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_943b5aa688f34806a7f582a71ba2525b }}/bc-eureka-server:${{ github.sha }}'

on: push
name: deploy
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Maven phasee
        run: mvn --batch-mode --update-snapshots verify

      - run: mkdir -p staging
      - run: cp ./target/*.jar ./staging/app.jar
      - run: cd staging && ls -l

      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

      - uses: actions/checkout@master
      - name: docker login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: jcninosalas/bc-eureka-server

      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./devops/Dockerfile